{"name": "Логин с неверным логином и паролем", "status": "passed", "parameters": [{"name": "key", "value": "'password'"}], "start": 1742460886612, "stop": 1742460886831, "uuid": "6ed91265-a800-4836-98e7-2055b254fcb4", "historyId": "41e756226a05ddbe0aa3b80dff907643", "testCaseId": "40f1be16d719b470d6b33a0dcfa51542", "fullName": "tests.test_login.TestLogin#test_login_invalid_data_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4NMQM7J"}, {"name": "thread", "value": "3120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}