{"name": "test_login_invalid_data_401[password]", "status": "passed", "parameters": [{"name": "key", "value": "'password'"}], "start": 1741766424455, "stop": 1741766424638, "uuid": "0cf66aba-b705-411e-8e4c-f7fa85c32e13", "historyId": "41e756226a05ddbe0aa3b80dff907643", "testCaseId": "40f1be16d719b470d6b33a0dcfa51542", "fullName": "tests.test_login.TestLogin#test_login_invalid_data_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4NMQM7J"}, {"name": "thread", "value": "18044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}